### ISSUE TITLE
Setting Custom Shell

### ISSUE THREAD

**Issue by mborejdo** [syedhassaanahmed/kiosk-demo-electron#1]
hey there! Thanks for your kiosk-biolerplate.

I am having problems running your Install-ShellLauncher.ps1 script.
I am running it in an elevated Powershell and invoke your Skript like this:
(a bit redacted)
```
 .\Install-ShellLauncher.ps1 kioskuser C:\Users\kioskuser\projects\myexe.exe
```
```
08/22/2017 19:42:19 Shell Launcher Enabled is set to True

08/22/2017 19:42:19 userName is kioskuser 

08/22/2017 19:42:19 Cashier_SID is S-1-5-21-3723059876-2847769641-3209782291-XXX
08/22/2017 19:42:19 exeName is C:\Users\kioskuser\projects\myexe.exe

08/22/2017 19:42:19 New settings for custom shells:

08/22/2017 19:42:19 @{Sid=S-1-5-21-3723059876-2847769641-3209782291-XXX
; Shell=C:\Users\kioskuser\projects\myexe.exe; DefaultAction=0}
```

Logging in now with my main user, Shows now a black Shell and not a Default Shell.
Also using kioskuser does not start myexe.exe.
Running the Uninstaller resets back the the Default Shell.

What is the best way to debug the Problem?

**Comment by syedhassaanahmed** [comment]
Hi @mborejdo 
I've made some changes to the script in last few days and have added file logging. Can you please retry and see if the problem still exists?
