### ISSUE TITLE
Windows 10 (1803) - Black screen on kiosk user launch

### ISSUE THREAD

**Issue by jim3ex** [syedhassaanahmed/kiosk-demo-electron#3]
Hi, we have successfully built and installed and set up the kiosk user, however, the electron app does not launch. We just get a black screen (explorer.exe does not launch). Here is the install log:

11/16/2018 09:34:43 Shell Launcher Enabled is set to True

11/16/2018 09:34:43 Default Shell is set to explorer.exe and the default action is set to 0

11/16/2018 09:34:43 UserName is kiosk

11/16/2018 09:34:43 Cashier_SID is S-1-5-21-64846573-2525431716-3060751376-1002

11/16/2018 09:34:43 ExeName is C:\Program Files (x86)\Kiosk Demo Electron\kiosk-demo-electron.exe

11/16/2018 09:34:43 New settings for custom shell:

11/16/2018 09:34:43 @{PSComputerName=JIMBO; __GENUS=2; __CLASS=WESL_UserSetting; __SUPERCLASS=; __DYNASTY=WESL_UserSetting; __RELPATH=WESL_UserSetting.Sid="S-1-5-21-64846573-2525431716-3060751376-1002"; __PROPERTY_COUNT=5; __DERIVATION=System.String[]; __SERVER=JIMBO; __NAMESPACE=root\standardcimv2\embedded; __PATH=\\JIMBO\root\standardcimv2\embedded:WESL_UserSetting.Sid="S-1-5-21-64846573-2525431716-3060751376-1002"; CustomReturnCodes=; CustomReturnCodesAction=; DefaultAction=0; Shell=C:\Program Files (x86)\Kiosk Demo Electron\kiosk-demo-electron.exe; Sid=S-1-5-21-64846573-2525431716-3060751376-1002; Scope=System.Management.ManagementScope; Path=\\JIMBO\root\standardcimv2\embedded:WESL_UserSetting.Sid="S-1-5-21-64846573-2525431716-3060751376-1002"; Options=System.Management.ObjectGetOptions; ClassPath=\\JIMBO\root\standardcimv2\embedded:WESL_UserSetting; Properties=System.Management.PropertyDataCollection; SystemProperties=System.Management.PropertyDataCollection; Qualifiers=System.Management.QualifierDataCollection; Site=; Container=}

**Comment by sladeodark** [comment]
Glad you are interested in this solution, I had the same result. Lately I've been trying the full delivery via InTune methods using the deployment progress preview feature. It's working much more effectively. It appears that I only need to add in a more effective custom action to my MSI that will force the reboot. Have you tried this way yet? I should also mention that I could not get it right until I got to professional MSI packaging tool. Advanced installer was worth every bit of the $3,000 I paid for it because it is virtually Limitless and its power.

**Comment by jim3ex** [comment]
UPDATE: We have it working! The issue, for us at least, we the Windows 10 version. We were testing on Windows 10 Pro (black screen). Tried on Windows 10 Enterprise (See https://docs.microsoft.com/en-us/windows-hardware/customize/enterprise/shell-launcher) and it works. Strange that there are no errors thrown at any point with Windows 10 Pro!

**Comment by sladeodark** [comment]
Wow that is awesome, sir. Can we chat on slack about your setup?

**Comment by syedhassaanahmed** [comment]
Thanks @jim3ex 
I can update the ReadMe with Windows 10 Enterprise. Should we mark the issue as closed?

**Comment by jim3ex** [comment]
Yes please. And thanks again for the excellent work!!
